variable "prefix" {
  type = string
}

variable "environment" {
  type = string
  default = "dev"
}

variable "omop_rg_location" {
  type = string
  default = "westus2"
}

variable "omop_password" {
  type = string
}

variable "config_local_path" {
  # Note that for my example this is expected to be the full path
  # to the file, not just the filename. Terraform idiom is to be
  # explicit about this sort of thing, rather than relying on
  # environment variables like HOME.
  type = string
  default = "../config/config-local.js"
}

variable "config_gis_path" {
  type = string
  default = "../config/config-gis.js"
}

locals {
  config-local = <<-EOT
    // Generated by TF
    define([], function () {
      var configLocal = {};

      // clearing local storage otherwise source cache will obscure the override settings
      localStorage.clear();

      var getUrl = window.location;
      var baseUrl = getUrl.protocol + "//" + getUrl.host;

      // WebAPI
      configLocal.api = {
        name: 'OHDSI',
        url: baseUrl + '/WebAPI/'
      };

      configLocal.cohortComparisonResultsEnabled = false;
      configLocal.userAuthenticationEnabled = false;
      configLocal.plpResultsEnabled = false;

      return configLocal;
    });
  EOT

  config-gis = <<-EOT
    // Generated by TF
  EOT
}

variable "omop_db_size" {
  type = string
  default = 20 # max size gb
}

variable "omop_db_sku" {
  type = string
  default = "BC_Gen5_10"
}

variable log_file {
  description = "Log file name to create with the seeding results."
  default     = "db-init.log"
}

variable "docker_image" {
  description = "Docker image for OHDSI WebAPI and Web tools"
  default = "yradsmikham/ohdsi-webapi-and-webtools"
}

variable "docker_image_tag" {
  description = "Docker image tag for OHDSI WebAPI and Web tools"
  default = "latest"
}
